steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-quant-service/app:$BUILD_ID', '.']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-quant-service/app:$BUILD_ID']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pairs-trading-quant-service'
  - '--image'
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-quant-service/app:$BUILD_ID'
  - '--region'
  - 'europe-west4'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'europe-west4-docker.pkg.dev/$PROJECT_ID/pairs-trading-quant-service/app:$BUILD_ID'